import type { AnalysisReport, RemediationItem } from "./types";
import type { FunctionId } from "@clrposture/core";

const FUNCTION_ORDER: FunctionId[] = ["GV", "ID", "PR", "DE", "RS", "RC"];

const FUNCTION_LABELS: Record<FunctionId, string> = {
  GV: "Govern",
  ID: "Identify",
  PR: "Protect",
  DE: "Detect",
  RS: "Respond",
  RC: "Recover",
};

function tierLabel(avg: number): string {
  const t = Math.round(avg);
  const labels: Record<number, string> = {
    1: "T1 — Partial",
    2: "T2 — Risk Informed",
    3: "T3 — Repeatable",
    4: "T4 — Adaptive",
  };
  return labels[t] ?? `T${t}`;
}

function gapBlock(item: RemediationItem): string {
  const lines: string[] = [
    `### ${item.subcategoryId}  T${item.currentTier} → T${item.targetTier}`,
  ];
  item.steps.forEach((step, i) => {
    lines.push(`${i + 1}. ${step}`);
  });
  return lines.join("\n");
}

function bucketSection(
  heading: string,
  items: RemediationItem[]
): string | null {
  if (items.length === 0) return null;
  const blocks = items.map(gapBlock).join("\n\n");
  return `## ${heading}\n\n${blocks}`;
}

export function reportToMarkdown(
  report: AnalysisReport,
  industry: string
): string {
  const date = new Date().toISOString().slice(0, 10);

  // LLM context block — gives a model reading this document enough background
  // to reason about priorities, draft tickets, or explain gaps to stakeholders.
  const context = [
    `# Clrposture Gap Report`,
    ``,
    `**Industry:** ${industry}  `,
    `**Framework:** NIST CSF 2.0  `,
    `**Assessment date:** ${date}  `,
    `**Assessment ID:** ${report.assessmentId}`,
    ``,
    `This is a NIST CSF 2.0 gap report generated by Clrposture. It shows the ` +
      `delta between the organization's current cybersecurity posture (Tier 1–4 ` +
      `per subcategory) and the target profile for the ${industry} industry. ` +
      `Each gap includes numbered remediation steps ordered from current tier ` +
      `toward the target. Gaps are bucketed by urgency: **Immediate** (delta ≥ 3), ` +
      `**Short-term** (delta = 2), and **Strategic** (delta = 1).`,
  ].join("\n");

  // Function-score summary table
  const tableRows = FUNCTION_ORDER.map((fn) => {
    const s = report.byFunction[fn];
    const current = s ? tierLabel(s.currentAvg) : "—";
    const target = s ? tierLabel(s.targetAvg) : "—";
    const gaps = s ? String(s.gapCount) : "—";
    return `| ${fn} | ${FUNCTION_LABELS[fn]} | ${current} | ${target} | ${gaps} |`;
  });

  const scoreTable = [
    `## Scores by Function`,
    ``,
    `| Function | Name | Current | Target | Gaps |`,
    `| --- | --- | --- | --- | --- |`,
    ...tableRows,
  ].join("\n");

  const weakest = report.remediationPlan.weakestFunction;
  const weakestNote = weakest
    ? `\n> **Weakest function:** ${weakest.id} — ${FUNCTION_LABELS[weakest.id]} ` +
      `(avg T${weakest.currentAvg.toFixed(1)}, ${weakest.gapCount} gaps)\n`
    : "";

  const sections = [
    context,
    scoreTable + weakestNote,
    bucketSection("Immediate  (gap ≥ 3 tiers)", report.remediationPlan.immediate),
    bucketSection("Short-term  (gap = 2 tiers)", report.remediationPlan.shortTerm),
    bucketSection("Strategic  (gap = 1 tier)", report.remediationPlan.strategic),
  ].filter(Boolean);

  return sections.join("\n\n---\n\n");
}
